spring:
    profiles:
        active:
        - dev
---
server:
    port: 8001

spring:
    profiles: dev
    application:
        name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver
        url: jdbc:mysql://localhost:3306/cloudDB01
        username: root
        password: 123456
        dbcp2:
            min-idle: 5
            inital-size: 5
            max-total: 5
            max-wait-millis: 200
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.atguigu.springcloud.entities
    mapper-location:
    - classpath: mybatis/mapper/**/*.xml

eureka:
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/  
---
server:
    port: 7001  #注册中心占用7001端口，冒号后面必须要有空格
    
spring:
    profiles: test
    application:
        name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver
        url: jdbc:mysql://localhost:3306/cloudDB01
        username: root
        password: 123456
        dbcp2:
            min-idle: 5
            inital-size: 5
            max-total: 5
            max-wait-millis: 200
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.atguigu.springcloud.entities
    mapper-location:
    - classpath: mybatis/mapper/**/*.xml

eureka:
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/  
        
